- name: Create Azure VM
  hosts: localhost
  connection: local
#  vars:
#    azure:
#      rg: myResourceGroup
#      location: centralus
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ azure.rg }}"
      location: "{{ azure.location }}"
